const EXAM_DATA = [
  {
    id: '1-1',
    title: '1. Dönem 1. Sınav',
    summary: '<b>E-Ticaret:</b> Mal/hizmet değişiminin internete taşınmasıdır. B2B, B2C ve C2C modelleri mevcuttur. <br><br><b>Güvenlik:</b> SSL sertifikaları veri şifreleme için zorunludur. İş planı, hedef kitle ve pazarlama stratejileri e-ticaretin temelidir.',
    questions: [
      { q: "E-ticaretin geleneksel ticarete göre en büyük avantajı nedir?", a: "7/24 kesintisiz satış ve coğrafi sınırları aşma imkanı." },
      { q: "B2B modeli nedir?", a: "İki işletme arasındaki ticari ilişkiyi ifade eder." },
      { q: "Bir e-ticaret iş planında neler olmalıdır?", a: "Hedef kitle, bütçe, pazarlama stratejisi ve risk analizi." },
      { q: "E-ticaret altyapı bileşenleri nelerdir?", a: "Sunucu, veri tabanı, yazılım ve ağ bağlantısı." },
      { q: "SSL sertifikası ne işe yarar?", a: "Kullanıcı bilgileri ile banka arasındaki iletişimi şifreleyerek korur." },
      { q: "Elektronik pazarlama yöntemlerinden üçünü sayınız.", a: "Sosyal medya reklamları, SEO ve e-posta pazarlama." },
      { q: "Sanal POS kavramını açıklayınız.", a: "Fiziksel POS cihazının web üzerindeki yazılımsal karşılığıdır." },
      { q: "E-ticarette en yaygın güvenlik tehdidi nedir?", a: "Phishing (Oltalama) ve kötü amaçlı yazılımlar." },
      { q: "E-ticaret hukuki düzenlemeleri neden gereklidir?", a: "Tüketici haklarını korumak ve ticari güveni sağlamak için." },
      { q: "Domain ve Hosting arasındaki fark nedir?", a: "Domain sitenin adıdır, Hosting ise sitenin dosyalarının barındığı dijital alandır." }
    ],
    flashcards: [
      { front: "Ticaret", back: "Kazanç amaçlı mal/hizmet değişimi." },
      { front: "E-Ticaret", back: "Elektronik ortamda yapılan ticaret." },
      { front: "B2B", back: "İşletmeden işletmeye ticaret." },
      { front: "B2C", back: "İşletmeden tüketiciye ticaret." },
      { front: "C2C", back: "Tüketiciden tüketiciye ticaret (Örn: 2. el)." },
      { front: "İş Planı", back: "Girişimin yol haritası." },
      { front: "Domain", back: "Web sitesinin adresi (Örn: .com)." },
      { front: "Hosting", back: "Sitenin dosyalarının barındığı alan." },
      { front: "SSL", back: "Veri trafiğini şifreleyen güvenlik protokolü." },
      { front: "Ödeme Yöntemi", back: "Kredi kartı, EFT, kapıda ödeme." },
      { front: "SEO", back: "Arama motoru optimizasyonu." },
      { front: "SEM", back: "Arama motoru pazarlaması (Reklamlar)." },
      { front: "Sanal POS", back: "İnternette kartla ödeme alma sistemi." },
      { front: "Hazır Paket", back: "Kullanıma hazır e-ticaret yazılımları." },
      { front: "Güvenlik Tehdidi", back: "Phishing, zararlı yazılımlar." },
      { front: "Lojistik", back: "Depolama ve sevkiyat süreci." },
      { front: "Envanter", back: "Stokların takibi ve kontrolü." },
      { front: "Lojistik", back: "Ürünün depolanması ve sevkiyat süreci." },
      { front: "SEM", back: "Arama motoru reklamcılığı." },
      { front: "Phishing", back: "Oltalama yoluyla veri hırsızlığı." }
    ]
  },
  {
    id: '1-2',
    title: '1. Dönem 2. Sınav',
    summary: '<b>Etik ve Güvenlik:</b> Sosyal medyada özel hayatın gizliliği ve dürüstlük esastır. <br><br><b>Siber Tehditler:</b> Siber zorbalık ve kişisel veri ihlallerine karşı 2FA (iki faktörlü doğrulama) ve güçlü şifreler kullanılmalıdır.',
    questions: [
      { q: "Bilişim etiğinin temel amacı nedir?", a: "Teknoloji kullanımında hak ve özgürlüklere saygılı bir ortam yaratmak." },
      { q: "Siber zorbalığa maruz kalan bir öğrenci ne yapmalıdır?", a: "Zorbalığı yapanı engellemeli ve durumu güvenilir bir yetişkine bildirmelidir." },
      { q: "Güçlü bir şifre nasıl oluşturulur?", a: "Harf, rakam ve sembollerden oluşan, en az 8-12 karakterli şifrelerle." },
      { q: "Dijital dönüşüm işletmelere ne kazandırır?", a: "Verimlilik artışı ve yeni pazar imkanları." },
      { q: "Bilgi güvenliğinin üç temel öğesi nedir?", a: "Gizlilik, bütünlük ve erişilebilirlik." },
      { q: "Sosyal medyada etik dışı paylaşımlara örnek veriniz.", a: "Başkasının fotoğrafını izinsiz paylaşmak, sahte haber yaymak." },
      { q: "Dijital marka yönetimi neden önemlidir?", a: "Markanın hedef kitle nezdindeki güvenini ve bilinirliğini artırır." },
      { q: "Antivirüs yazılımları hangi tehditleri engeller?", a: "Trojan, worm ve ransomware gibi zararlı yazılımları." },
      { q: "Unutulma Hakkı nedir?", a: "Kişinin internetteki verilerinin silinmesini talep etme hakkıdır." },
      { q: "Siber zorbalıkla mücadelede en etkili yöntem nedir?", a: "Bilinçli internet kullanımı ve güvenlik ayarlarının doğru yapılması." }
    ],
    flashcards: [
      { front: "Bilişim Etiği", back: "Bilgisayar dünyasındaki ahlaki kurallar." },
      { front: "Dijital Haklar", back: "Erişim ve ifade özgürlüğü." },
      { front: "Netiquette", back: "İnternet nezaket kuralları." },
      { front: "Bilgi Güvenliği", back: "Verilerin izinsiz erişime karşı korunması." },
      { front: "Kişisel Veri", back: "Bireyi tanımlayan her türlü bilgi." },
      { front: "Siber Zorbalık", back: "Dijital cihazlarla yapılan taciz/şiddet." },
      { front: "Antivirüs", back: "Virüsten koruma yazılımları." },
      { front: "Dijital Marka", back: "Bir kurumun internetteki kimliği." },
      { front: "Dijital Dönüşüm", back: "Teknolojinin iş süreçlerine entegrasyonu." },
      { front: "2FA", back: "İki faktörlü doğrulama katmanı." },
      { front: "İtibar Yönetimi", back: "Marka hakkındaki algıyı yönetme." },
      { front: "Dijital Ayak İzi", back: "İnternette bırakılan her türlü iz." },
      { front: "Telif Hakkı", back: "Eser sahibinin yasal hakları." },
      { front: "Spam", back: "İstenmeyen yığın mesajlar." },
      { front: "Hacker", back: "Sistemlere izinsiz giren kişi." },
      { front: "Filtreleme", back: "Uygunsuz içeriklerin engellenmesi." },
      { front: "Parola", back: "Harf-rakam-sembol içeren güçlü şifre." },
      { front: "Gizlilik", back: "Özel hayatın korunması prensibi." },
      { front: "Siber Şiddet", back: "Dijital ortamda hakaret veya tehdit." },
      { front: "Dijital Kimlik", back: "Kişinin sanal dünyadaki varlığı." }
    ]
  },
  {
    id: '2-1',
    title: '2. Dönem 1. Sınav',
    summary: '<b>Yönetim:</b> İçerik planı, takvim ve hedef kitle tespiti sosyal medyanın bel kemiğidir. <br><br><b>Analiz:</b> Etkileşim, erişim ve gösterim gibi metrikler raporlanır. Kriz anlarında şeffaf bir iletişim stratejisi uygulanır.',
    questions: [
      { q: "Bir içerik planı takviminde neler yer almalıdır?", a: "Paylaşım tarihi, saati, kanal ismi, içerik metni ve görseli." },
      { q: "Hedef kitle tespiti neden yapılır?", a: "İçeriğin doğru kişilere ulaşmasını sağlayarak verimliliği artırmak için." },
      { q: "Sosyal medya raporlamasında hangi metrikler kullanılır?", a: "Etkileşim oranı, takipçi artışı, erişim ve tıklama sayıları." },
      { q: "Kriz iletişimi kampanyasında ilk adım nedir?", a: "Krizin kaynağını belirlemek ve hızlı bir resmi açıklama yapmak." },
      { q: "Veri ve enformasyon arasındaki fark nedir?", a: "Veri hamdır, enformasyon ise verinin işlenmiş halidir." },
      { q: "Sosyal medya analiz araçları ne işe yarar?", a: "Rakip analizi yapmaya ve kitle davranışlarını anlamaya yardımcı olur." },
      { q: "İçerik kategorileri neden oluşturulur?", a: "Sayfanın içerik çeşitliliğini dengede tutmak için." },
      { q: "Bir kriz anında sessiz kalmak doğru mudur?", a: "Yanlıştır; şeffaf iletişim krizin büyümesini engeller." },
      { q: "Etkileşim Oranı nasıl hesaplanır?", a: "Toplam etkileşimin toplam erişime bölünmesiyle." },
      { q: "Veri toplama yöntemlerinden birini sayınız.", a: "Anketler veya platform içi istatistik araçları." }
    ],
    flashcards: [
      { front: "İçerik Planı", back: "Ne zaman ne paylaşılacağının şeması." },
      { front: "Hedef Kitle", back: "İçeriğin ulaşması istenen grup." },
      { front: "İçerik Takvimi", back: "Paylaşımların tarih bazlı çizelgesi." },
      { front: "Analitik", back: "Performans ölçüm süreci." },
      { front: "Raporlama", back: "Verilerin anlamlı tabloya dökülmesi." },
      { front: "Kriz İletişimi", back: "Olumsuz durumları yönetme süreci." },
      { front: "Veri (Data)", back: "Henüz işlenmemiş ham bilgi." },
      { front: "Enformasyon", back: "Anlamlandırılmış veri." },
      { front: "Bilgi (Knowledge)", back: "Deneyimle pekişmiş enformasyon." },
      { front: "Etkileşim", back: "Beğeni, yorum ve paylaşım sayıları." },
      { front: "Erişim", back: "İçeriği gören tekil kişi sayısı." },
      { front: "Gösterim", back: "İçeriğin ekrana gelme sayısı." },
      { front: "Demografi", back: "Yaş, cinsiyet, konum verileri." },
      { front: "Algoritma", back: "İçeriği öne çıkarma kuralları." },
      { front: "İçerik Üretimi", back: "Video, metin veya görsel oluşturma." },
      { front: "Geri Bildirim", back: "Kullanıcılardan gelen tepkiler." },
      { front: "Kanal Seçimi", back: "İçeriğe uygun platformu belirleme." },
      { front: "Takipçi Artışı", back: "Kitle büyüme hızı." },
      { front: "Tıklama (CTR)", back: "Bağlantılara tıklanma oranı." },
      { front: "Mentions", back: "Markadan bahsedilme sayısı." }
    ]
  },
  {
    id: '2-2',
    title: '2. Dönem 2. Sınav',
    summary: '<b>Görselleştirme:</b> Verilerin hızlı anlaşılması için grafikler kullanılır. <br><br><b>Grafik Türleri:</b> Zaman için Çizgi, karşılaştırma için Sütun, oranlar için Pasta grafik tercih edilir. Radar ve Huni gibi gelişmiş türler de vardır.',
    questions: [
      { q: "Zaman içindeki satış değişimini en iyi hangi grafik gösterir?", a: "Çizgi grafik." },
      { q: "Histogram grafiği hangi amaçla kullanılır?", a: "Verilerin sıklığını (dağılımını) göstermek için." },
      { q: "Pasta grafik hangi durumlarda tercih edilmez?", a: "Kategori sayısı çok fazla olduğunda karmaşaya neden olduğu için." },
      { q: "Radar Grafik ne için kullanılır?", a: "Sporcu performansları gibi çoklu yeteneklerin kıyaslanması için." },
      { q: "Veri görselleştirmenin temel avantajı nedir?", a: "Karmaşık bilgilerin hızlı ve kolay anlaşılmasını sağlamak." },
      { q: "Huni grafiği hangi sektörlerde popülerdir?", a: "Satış ve pazarlama süreçlerinin takibinde." },
      { q: "Veri toplama kaynakları neler olabilir?", a: "Resmi kurumlar (TÜİK vb.), internet siteleri ve anketler." },
      { q: "Ağaç Haritası grafiğinin özelliği nedir?", a: "Hiyerarşik verileri dikdörtgenlerle görselleştirmesi." },
      { q: "Grafik öncesi 'veri hazırlama'da ne yapılır?", a: "Hatalı veriler temizlenir ve tablo formatına sokulur." },
      { q: "Bileşik grafikler ne zaman kullanılır?", a: "İki farklı birimdeki veriyi (Örn: Yağış ve Sıcaklık) tek grafikte göstermek için." }
    ],
    flashcards: [
      { front: "Sütun Grafik", back: "Kategorileri karşılaştırma aracı." },
      { front: "Çizgi Grafik", back: "Zaman içindeki eğilimleri gösterir." },
      { front: "Pasta Grafik", back: "Bir bütünün parçalarını/oranlarını gösterir." },
      { front: "Histogram", back: "Veri dağılım sıklığı grafiği." },
      { front: "Radar Grafik", back: "Merkezden yayılan çoklu değişkenler." },
      { front: "Huni Grafiği", back: "Aşamalı azalmaları (satış hunisi) gösterir." },
      { front: "Şelale Grafik", back: "Kümülatif değişim etkisini gösterir." },
      { front: "Ağaç Haritası", back: "Hiyerarşik verileri kutularla gösterir." },
      { front: "Görselleştirme", back: "Verilerin grafiksel sunumu." },
      { front: "Veri Kümesi", back: "Birbiriyle ilişkili veriler topluluğu." },
      { front: "Kategorik Veri", back: "Sayısal olmayan sınıflar (Şehirler vb.)." },
      { front: "Sayısal Veri", back: "Ölçülebilir değerler (Boy, kilo vb.)." },
      { front: "Bileşik Grafik", back: "İki farklı grafik türünün birleşimi." },
      { front: "Güneş Işığı", back: "Hiyerarşik halka grafik türü." },
      { front: "XY Dağılım", back: "İki değişken arasındaki ilişki." },
      { front: "Hisse Senedi", back: "Borsa verilerini gösteren özel grafik." },
      { front: "Kutu Grafik", back: "Veri dağılımını ve uç değerleri gösterir." },
      { front: "Veri Temizleme", back: "Hatalı veya eksik verilerin ayıklanması." },
      { front: "Veri Analizi", back: "Veriden anlam çıkarma süreci." },
      { front: "Grafik Seçimi", back: "Veriye uygun görsel türünü belirleme." }
    ]
  }
];

window.EXAM_DATA = EXAM_DATA;
